services:
  frontend:
    image: ghcr.io/mjnd1/ai-town-frontend:latest
    platform: linux/arm64
    ports:
      - "${FRONTENDPORT}:5173"
    environment:
      - VITE_CONVEX_URL=${VITE_CONVEX_URL}
      - CONVEX_SELF_HOSTED_ADMIN_KEY=${CONVEX_SELF_HOSTED_ADMIN_KEY}
      - CONVEX_SELF_HOSTED_URL=${CONVEX_SELF_HOSTED_URL}
    networks:
      - ai-town-network

  backend:
    image: ghcr.io/mjnd1/ai-town-backend:latest
    platform: linux/arm64
    ports:
      - "${CONVEX_PORT:-9081}:3210"
      - "${SITE_PROXY_PORT:-9003}:3211"
    volumes:
      - data:/convex/data
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME:-}
      - INSTANCE_SECRET=${INSTANCE_SECRET:-}
      - CONVEX_RELEASE_VERSION_DEV=${CONVEX_RELEASE_VERSION_DEV:-}
      - ACTIONS_USER_TIMEOUT_SECS=${ACTIONS_USER_TIMEOUT_SECS:-}
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN}
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN}
      - DATABASE_URL=${DATABASE_URL:-}
      - DISABLE_BEACON=${DISABLE_BEACON}
    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 5s
    networks:
      - ai-town-network

  dashboard:
    image: ghcr.io/mjnd1/ai-town-dashboard:latest
    platform: linux/arm64
    ports:
      - "${DASHBOARD_PORT:-9005}:6791"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${VITE_CONVEX_URL}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ai-town-network

volumes:
  data:
    # 用本地驱动
    driver: local
    # 给驱动加“特殊指令”，让它不再是 Docker 内部卷
    driver_opts:
      # 表示不是 Docker 自己建的文件系统
      type: none
      # 当前项目根目录下的 data 文件夹
      device: ./data
      # “o” 是 options 的缩写，bind = 绑定挂载（把主机文件夹强行绑到容器里）
      o: bind

networks:
  ai-town-network:
    driver: bridge
